### ISSUE TITLE
warning: unknown `doc` attribute `summary`

### ISSUE THREAD

**Issue by 5anchezzz** [nerzh/ton-client-ruby#3]
При запуске cargo build --release появляются вот такие варнинги. Можно их игнорить или лучше поправить че-то?
![image](https://user-images.githubusercontent.com/49248922/119347579-6039ef00-bca4-11eb-9a1b-91958725cc3f.png)

**Comment by nerzh** [comment]
если знаешь rust можешь, конечно, поправить и сделать им пуллреквест

Пн, 24 мая 2021 г. в 15:27, Alex Zhuk ***@***.***>:

**Comment by nerzh** [comment]
если знаешь rust можешь, конечно, поправить и сделать им пуллреквест

**Comment by 5anchezzz** [comment]
Привет! Ты не против, если я тут покидаю вопросиков в ишъю? Еще там с маком проблема какая-то(((

**Comment by 5anchezzz** [comment]
Понял, благодарю)))
