### ISSUE TITLE
[__NSCFConstantString initialize]

### ISSUE THREAD

**Issue by 5anchezzz** [nerzh/ton-client-ruby#4]
При деплое контракта `client.processing.process_message` и отправке сообщения `client.processing.send_message()` на MacOS Catalina 10.15.7 падает приложение:
	
`objc[25674]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[25674]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
`

В чем может быть проблема?

![image](https://user-images.githubusercontent.com/49248922/119348568-b9eee900-bca5-11eb-96c6-c4b84acda592.png)

**Comment by nerzh** [comment]
возможно, у тебя проблема с многопоточностью, учитывай, что все методы асинхронные. В моем первом примере тебе есть пример вызова метода синхронно, возможно это тебе подойдет больше через TonClient.callLibraryMethodSync

**Comment by 5anchezzz** [comment]
Спасибо!
