### ISSUE TITLE
Нода

### ISSUE THREAD

**Issue by 5anchezzz** [nerzh/ton-client-ruby#5]
Олег, привет! Подскажи, пожалуйста, могу ли я через sdk отправлять запросы на обработку на конкретную ноду? В  server_address в конфигах можно прям указать ipшник ноды или там просто адрес сети указывается "main.ton.dev"/"net.ton.dev" и т.д.? Если указываешь "main.ton.dev", где обрабатывается запрос?

**Comment by nerzh** [comment]
Привет, server_address уже устарел, сейчас надо передавать массив эндпоинтов endpoints тк он не один, например для мейна это "https://main2.ton.dev", "https://main3.ton.dev" - это первое.

Второе - да, можешь в эндпоинты передать свои адреса и конектиться к ним

**Comment by 5anchezzz** [comment]
Олег, спасибо тебе большое!!!
